#https://github.com/bitnami/charts/tree/master/bitnami/external-dns/#external-dns-parameters
provider: aws
aws:
  zoneType: public
sources:
  - crd
logLevel: debug
# annotationFilter: type=global
crd:
  create: false
  apiversion: kuadrant.dev/v1
  kind: DNSRecord
policy: sync
registry: txt
txtPrefix: kcp-glbc-
