// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kuadrant/kcp-glbc/pkg/apis/kuadrant/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DomainVerificationLister helps list DomainVerifications.
// All objects returned here must be treated as read-only.
type DomainVerificationLister interface {
	// List lists all DomainVerifications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DomainVerification, err error)
	// Get retrieves the DomainVerification from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DomainVerification, error)
	DomainVerificationListerExpansion
}

// domainVerificationLister implements the DomainVerificationLister interface.
type domainVerificationLister struct {
	indexer cache.Indexer
}

// NewDomainVerificationLister returns a new DomainVerificationLister.
func NewDomainVerificationLister(indexer cache.Indexer) DomainVerificationLister {
	return &domainVerificationLister{indexer: indexer}
}

// List lists all DomainVerifications in the indexer.
func (s *domainVerificationLister) List(selector labels.Selector) (ret []*v1.DomainVerification, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DomainVerification))
	})
	return ret, err
}

// Get retrieves the DomainVerification from the index for a given name.
func (s *domainVerificationLister) Get(name string) (*v1.DomainVerification, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("domainverification"), name)
	}
	return obj.(*v1.DomainVerification), nil
}
