apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dnsendpoint-weighted-health
  annotations:
    type: global
spec:
  endpoints:
    - dnsName: dnsendpoint-weighted-health.mn.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 52.215.108.61
      providerSpecific:
        - name: "aws/weight"
          value: "100"
        - name: "aws/evaluate-target-health"
          value: "true"
        - name: "aws/health-check-id"
          value: "5d6c8932-620c-41ea-9c91-8780d8b62455"
      labels:
        id: 52.215.108.61
      targets:
        - 52.215.108.61
    - dnsName: dnsendpoint-weighted-health.mn.hcpapps.net
      recordTTL: 60
      recordType: A
      setIdentifier: 52.30.101.221
      providerSpecific:
        - name: "aws/weight"
          value: "100"
        - name: "aws/evaluate-target-health"
          value: "true"
        - name: "aws/health-check-id"
          value: "5d6c8932-620c-41ea-9c91-8780d8b62455"
      labels:
        id: 52.30.101.221
      targets:
        - 52.30.101.221
