// begin header
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:numbered:
:toc: macro
:toc-title: pass:[<b>Table of Contents</b>]
// end header
= HighDNSLatencyAlert

toc::[]

== Description

The source of the alert is the `glbc_route_53_*` metric. It fires when there is high latency rate on the requests made.
The alert will be triggered if requests are taking longer than 0.5 seconds. This usually means, the DNS provider is not responding, metrics is misconfigured, or the metrics endpoint is not responding.

== Prerequisites

* Access to the physical cluster where GLBC should be running

== Execute/Resolution

. Check the DNS & namespace for indications of problems.
+
[source,sh]
----
kubectl logs deployment/kcp-glbc-controller-manager
kubectl get events
----
If found a _5xx_ type error, proceed to verify the https://health.aws.amazon.com/health/status[AWS Health Status] for any know outages or issues.

. Check the configuration (aws key & secret) to ensure they are correct.

. Verify the https://health.aws.amazon.com/health/status[AWS Health Status]

== Validate

. Check the alert is no longer firing.
