[[grafana]]
= Grafana

The https://github.com/grafana-operator/grafana-operator[Grafana operator] is used to install and configure grafana as part of the KCP GLBC monitoring stack.

[[prerequisites]]
== Prerequisites

Prometheus instance, configured to integrate with the KCP GLBC instance deployed on the same cluster, see link:monitoring.adoc[monitoring].

[[kubernetes]]
=== Kubernetes

Installations on Kubernetes require a prometheus instance deployed and configured on the target cluster.
The following will install the https://github.com/prometheus-operator/kube-prometheus[kube-prometheus monitoring stack] as part of the installation.
Note, only prometheus is required, please refer to the link:monitoring.adoc[monitoring] guide for other installation options.

Deploy prometheus and grafana
[source,console]
----
$ ./bin/kustomize build config/observability/kubernetes/ | kubectl apply -f -
----
Note: You might need to do this a couple of times.

// Check Grafana
$ kubectl get deployments -n kcp-glbc-observability
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
grafana-deployment                    1/1     1            1           54s
grafana-operator-controller-manager   1/1     1            1           2m14s

If testing on a https://kind.sigs.k8s.io//[kind] cluster, the console should be accessible from http://grafana.127.0.0.1.nip.io:<node port> (user:admin, password: admin)


[[openshift]]
=== OpenShift

Installations on OpenShift make use of the pre-configured https://docs.openshift.com/container-platform/4.10/monitoring/monitoring-overview.html[monitoring stack] and expect https://docs.openshift.com/container-platform/4.10/monitoring/enabling-monitoring-for-user-defined-projects.html[user workload monitoring] to be enabled.

Extract a token to connect to the user workload prometheus:
[source,console]
----
$ SECRET=`oc get secret -n openshift-user-workload-monitoring | grep  prometheus-user-workload-token | head -n 1 | awk '{print $1 }'`
$ TOKEN=`echo $(oc get secret $SECRET -n openshift-user-workload-monitoring -o json | jq -r '.data.token') | base64 -d`
----

Update grafana prometheus data source with the token extracted above:
[source,console]
----
$ sed -i "s/CHANGEME/$TOKEN/" config/observability/openshift/grafana/prometheus-grafanadatasource.yaml
----

Deploy grafana
[source,console]
----
$ ./bin/kustomize build config/observability/openshift/ | kubectl apply -f -
----
Note: You might need to do this a couple of times.

// Check Grafana
[source,console]
----
$ kubectl get deployments -n kcp-glbc-observability
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
grafana-deployment                    1/1     1            1           54s
grafana-operator-controller-manager   1/1     1            1           2m14s
$ kubectl get routes -n kcp-glbc-observability
NAME      HOST/PORT                                         PATH   SERVICES          PORT    TERMINATION   WILDCARD
grafana   grafana-kcp-glbc-observability.apps-crc.testing          grafana-service   https   reencrypt     None
----

If testing on a https://crc.dev/crc/[crc] cluster, the console should be accesible from https://grafana-kcp-glbc-observability.apps-crc.testing (OpenShift login user: kubadmin)

