name: Smoke Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  schedule:
    # Runs twice a day at 06:13 and 18:13
    - cron: "13 6,18 * * *"

jobs:
  ingress_test:
    name: Ingress Test
    environment: ${{ inputs.environment || 'unstable' }}
    concurrency: ${{ inputs.environment || 'unstable' }}
    runs-on: ubuntu-20.04
    env:
      AWS_DNS_PUBLIC_ZONE_ID: ${{ secrets.AWS_DNS_PUBLIC_ZONE_ID }}
      GLBC_DOMAIN: ${{ secrets.GLBC_DOMAIN }}
      GLBC_ENABLE_CUSTOM_HOSTS: ${{ secrets.GLBC_ENABLE_CUSTOM_HOSTS }}
      GLBC_EXPORT: ${{ secrets.GLBC_EXPORT }}
      GLBC_WORKSPACE: ${{ secrets.GLBC_WORKSPACE }}
      TEST_WORKSPACE: ${{ secrets.TEST_WORKSPACE }}
      TEST_TAGS: smoke,ingress
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.18
      - name: Setup Kubeconfig
        run: |
          make generate-test-oidc-kubeconfig \
              TEST_OIDC_KUBECONFIG=test.kubeconfig \
              TEST_KUBE_HOST=${{ secrets.TEST_KUBE_HOST }} \
              TEST_KUBE_OIDC_ISSUER_URL=${{ secrets.TEST_KUBE_OIDC_ISSUER_URL }} \
              TEST_KUBE_OIDC_CLIENT_ID=${{ secrets.TEST_KUBE_OIDC_CLIENT_ID }} \
              TEST_KUBE_OIDC_CLIENT_SECRET=${{ secrets.TEST_KUBE_OIDC_CLIENT_SECRET }}
          kubectl config --kubeconfig=test.kubeconfig get-contexts
          export KUBECONFIG="$(pwd)"/test.kubeconfig
          echo "KUBECONFIG=${KUBECONFIG}" >> $GITHUB_ENV
      - name: Run smoke tests
        run: |
          export KUBECONFIG=${{ env.KUBECONFIG }}
          make smoke TEST_TAGS=${{ env.TEST_TAGS }}
